version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.13.7
    steps:
      - checkout
      - run: python main.py
  
  test:
    docker:
      - image: cimg/python:3.13.7
    steps:
      - run: python test.py

workflows:
  Build_and_Test:
    jobs:
      - build
      - test:
          required:
            - build